version: '3.4'

networks:
  webapiservices:

volumes:
  myvolume:

services:
  hocviendb: 
    container_name: hocvien-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - myvolume:/var/otp/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dk1912@2002!
    networks:
      - webapiservices
    ports:
      - 8001:1433
  hocvienwebapi:
    container_name: hocvien-api
    image: ${DOCKER_REGISTRY-}hocvienwebapi
    build:
      context: .
      dockerfile: HocVienWebAPI/Dockerfile
    ports:
      - 18001:80
    networks:
      - webapiservices
    depends_on: 
      - hocviendb
    environment:
      - DB_HOST=hocviendb
      - DB_NAME=hocvien
      - DB_SA_PASSWORD=Dk1912@2002!


  daotaodb:
    container_name: daotao-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - myvolume:/var/otp/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dk1912@2002!
    networks:
      - webapiservices
    ports:
      - 8003:1433
  daotaowebapi:
    container_name: daotao-api
    image: ${DOCKER_REGISTRY-}daotaowebapi
    build:
      context: .
      dockerfile: DaoTaoWebAPI/Dockerfile
    ports:
      - 18002:80
    networks:
      - webapiservices
    depends_on: 
      - daotaodb
    environment:
      - DB_HOST=daotaodb
      - DB_NAME=daotao
      - DB_SA_PASSWORD=Dk1912@2002!

  giangviendb:
    container_name: giangvien-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - myvolume:/var/otp/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dk1912@2002!
    networks:
      - webapiservices
    ports:
      - 8005:1433
  giangvienwebapi:
    container_name: giangvien-api
    image: ${DOCKER_REGISTRY-}giangvienwebapi
    build:
      context: .
      dockerfile: GiangVienWebAPI/Dockerfile
    ports:
      - 18003:80
    networks:
      - webapiservices
    depends_on: 
      - giangviendb
    environment:
      - DB_HOST=giangviendb
      - DB_NAME=giangvien
      - DB_SA_PASSWORD=Dk1912@2002!

  lichnghidb:
    container_name: lichnghi-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - myvolume:/var/otp/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dk1912@2002!
    networks:
      - webapiservices
    ports:
      - 8007:1433
  lichnghiwebapi:
    container_name: lichnghi-api
    image: ${DOCKER_REGISTRY-}lichnghiwebapi
    build:
      context: .
      dockerfile: LichNghiWebAPI/Dockerfile
    ports:
      - 18004:80
    networks:
      - webapiservices
    depends_on: 
      - lichnghidb
    environment:
      - DB_HOST=lichnghidb
      - DB_NAME=lichnghi
      - DB_SA_PASSWORD=Dk1912@2002!

  ghidanh_doanhthudb:
    container_name: ghidanh_doanhthu-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - myvolume:/var/otp/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dk1912@2002!
    networks:
      - webapiservices
    ports:
      - 8009:1433
  ghidanh_doanhthu:
    container_name: ghidanh_doanhthu-api
    image: ${DOCKER_REGISTRY-}ghidanhdoanhthu
    build:
      context: .
      dockerfile: GhiDanh_DoanhThu/Dockerfile
    ports:
      - 18005:80
    networks:
      - webapiservices
    depends_on: 
      - ghidanh_doanhthudb
    environment:
      - DB_HOST=ghidanh_doanhthudb
      - DB_NAME=ghidanh_doanhthu
      - DB_SA_PASSWORD=Dk1912@2002!

  apigateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - 8001:80
    networks:
      - webapiservices

