version: '3.4'

services:
  hocvienwebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  daotaowebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

